@startuml

class 収支履歴 {
  日時
  収支
  入力()
  表示()
  出力()
}

class 残高 {
  金額
  表示()
  計算()
  出力()
}

class 口座 {
  銀行名
  支店名
  ユーザー情報
  入力()
  表示()
  出力()
}

class ユーザー情報 {
  口座番号
  暗証番号
}

口座 -> ユーザー情報

@enduml
